### ISSUE TITLE
Crash when calling equilibrate('TP')

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Cantera/cantera#130]
```
What steps will reproduce the problem?
1. Import the attached .cti
2. Set temperature to 300K, pressure to 1e5Pa, moleFractions to "CO2:1"
3. use equilibrate('TP') 

What is the expected output? What do you see instead?
I expect the equilibrium composition of the gas to be computed. Instead, I get 
a platform-dependent error message:

Windows:
Traceback (most recent call last):
  File "C:\...\thermo_error.py", line 39, in <module>
    gas.equilibrate('TP')
  File "C:\Python27\lib\site-packages\Cantera\ThermoPhase.py", line 317, in equilibrate
    rtol, maxsteps, maxiter, loglevel)
error: Error in thermo_equil

Linux:
Segmentation fault (core dumped)


What version of the product are you using? On what operating system?
svn r1924 on linux , python 2.7.3
svn r1906 on windows, python 2.7.2

Please provide any additional information below.
The attached script triggers the error. This of course depends on the content 
of the phase and more generally on the values of T,P. For example, the script 
runs fine if T=3000K is used instead of T=300K.

```

Original issue reported on code.google.com by `chdoi...@gmail.com` on 14 Nov 2012 at 10:21

Attachments:
co2.cti:

``` python
ideal_gas(name = "gas", 
 elements = "C O", 
 species = "nasa_gas:all", 
 options = "skip_undeclared_elements")
```

thermo_error.py:

``` python
# homogeneous equilibrium of a gas.
from Cantera import *
import numpy as np

# create an object representing the gas phase
gas = importPhase("co2.cti")

# set the initial state
pressure=1e5
temperature=300

#no crash observed when temperature=3000 (for example)
#temperature=3000

print '------------------------------------------------'
print "Expected behavior with vcs_equilibrate or equilibrate('xx',solver=1)"
print '------------------------------------------------'
#Expected behavior
gas.setMoleFractions("CO2:1")
gas.set(T=temperature, P=pressure)    
mix=Mixture([gas])
mix.vcs_equilibrate('TP')
print gas
#Expected behavior #2
print '------------------------------------------------'
print 'This also works'
print '------------------------------------------------'
gas.setMoleFractions("CO2:1")
gas.set(T=temperature, P=pressure)
gas.equilibrate('TP', solver=1)
print gas

#Unexpected behavior #1
print '------------------------------------------------'
print 'This fails, error: Error in thermo_equil'
print '------------------------------------------------'
gas.setMoleFractions("CO2:1")
gas.set(T=temperature, P=pressure)
gas.equilibrate('TP')
# gas.equilibrate('TP', solver=0) also fails.
print gas
```

**Comment by ischoegl** [comment]
This doesn't appear to be an issue any longer. Porting the code as

```python
# homogeneous equilibrium of a gas.
from cantera import *
import numpy as np

# create an object representing the gas phase
gas = Solution("co2.cti")

# set the initial state
pressure=1e5
temperature=300

#no crash observed when temperature=3000 (for example)
#temperature=3000

for solver in ['vcs', 'gibbs', 'auto']:

    print('------------------------------------------------')
    print("Equilibrating with option: " + solver)
    print('------------------------------------------------')

    #Expected behavior
    gas.TPX = temperature, pressure, "CO2:1"
    mix=Mixture([gas])
    try:
        mix.equilibrate('TP', solver=solver, max_steps=10000)
    except CanteraError as err:
        print(err)
    print(gas())
```
runs without problems (although the gibbs solver does not converge).

**Comment by speth** [comment]
Thanks for adding the script updated to use the current version of the Python module.

I think that the main thing that has changed here is that the logic of the "auto" option has been fixed so that it correctly retries with the "vcs" solver after a failure with the "gibbs" solver. The error from the "gibbs" solver seems to be the same as described in my comment from 2013. So the behavior has changed somewhat from the original report, but the underlying bug is still present.
