### ISSUE TITLE
Unable to load serialized mechanism where reactions contain undeclared third bodies

### ISSUE THREAD

**Issue by speth** [Cantera/cantera#1403]
**Problem description**

When adding reactions dynamically to a `Solution` object in Python, Cantera by default will ignore reactions with undeclared third bodies. However, the corresponding flag is not automatically set (if needed) when saving this `Solution` as a YAML file and the resulting file cannot be loaded without modification.

Specifically, the phase entry in the generated YAML file should contain the option:
```yaml
    skip-undeclared-third-bodies: true
```

**Steps to reproduce**

```python
import cantera as ct

### Reducing mechanism
gri30 = ct.Solution('gri30.yaml')
h2o2 = ct.Solution('h2o2.yaml')

reactions = []
dest_species = set(h2o2.species_names)
for R in gri30.reactions():
    if all(S in dest_species for S in (R.reactants | R.products).keys()):
        reactions.append(R)

gas = ct.Solution(thermo='ideal-gas', kinetics='gas', species=h2o2.species(),
                  reactions=reactions)

gas.write_yaml("reduced.yaml")
restored = ct.Solution("reduced.yaml")
```

**Behavior**

The following traceback is generated
```pytb
Traceback (most recent call last):
  File "/home/speth/src/cantera-related/undeclared_species.py", line 20, in <module>
    restored = ct.Solution("reduced.yaml")
  File "build/python/cantera/base.pyx", line 71, in cantera._cantera._SolutionBase.__cinit__
  File "build/python/cantera/base.pyx", line 128, in cantera._cantera._SolutionBase._cinit
  File "build/python/cantera/base.pyx", line 215, in cantera._cantera._SolutionBase._init_yaml
cantera._cantera.CanteraError:
*******************************************************************************
CanteraError thrown by addReactions:

*******************************************************************************
InputFileError thrown by Reaction::checkSpecies:
Error on line 189 of ./reduced.yaml:
Reaction '2 O + M <=> O2 + M'
defines third-body efficiencies for undeclared species: 'C2H6', 'CH4', 'CO', 'CO2'
|  Line |
|   184 |       rotational-relaxation: 4.0
|   185 | reactions:
|   186 |   - equation: 2 O + M <=> O2 + M
|   187 |     type: three-body
|   188 |     rate-constant: {A: 1.2e+11, b: -1.0, Ea: 0.0}
>   189 >     efficiencies: {AR: 0.83, C2H6: 3.0, CH4: 2.0, CO: 1.75, CO2: 3.6, H2: 2.4, H2O: 15.4}
                            ^
|   190 |   - equation: H + O + M <=> OH + M
|   191 |     type: three-body
|   192 |     rate-constant: {A: 5.0e+11, b: -1.0, Ea: 0.0}
*******************************************************************************
```
(plus similar errors for 6 other reactions).

**Workaround**

This problem can be worked around by setting the necessary flag as "user data". Adding the following line before calling `write_yaml` generates a mechanism file that can be loaded:

```py
gas.update_user_data({'skip-undeclared-third-bodies': True})
```

**System information**

- Cantera version: 2.6.0, or `main` branch at 7684653bb
- OS: Ubuntu 20.04
- Python 3.10 (conda-forge)

**Attachments**

**Additional context**

This is derived from a problem posted on the Users' Group: https://groups.google.com/g/cantera-users/c/ujcAgMT5Vgc

**Comment by ischoegl** [comment]
The *'workaround'* actually causes a segfault (at least on current `main`); see #1587.
