### ISSUE TITLE
Error compiling 3.0.0a5 on Ubuntu 20.04 using Python3.8

### ISSUE THREAD

**Issue by wandadars** [Cantera/cantera#1506]
**Problem description**

Cloned the repository today (06-16-23), and did a "scons build" without any additional variables. The build process exits with an error regarding the cythonization of a file and it mentions "Syntax error in C variable declaration".

**Steps to reproduce**

1.) Clone repository
2.) Enter directory and type "scons build"

**Behavior**

The error that happens is shown below.
```

Substituting vars from build/python/setup.cfg.in to build/python/setup.cfg
/usr/bin/python3 -c "import Cython.Build; Cython.Build.cythonize(r'build/python/cantera/_cantera.pyx', compiler_directives={'binding': True})"
Compiling build/python/cantera/_cantera.pyx because it changed.
[1/1] Cythonizing build/python/cantera/_cantera.pyx
g++ -o build/temp-py/_cantera.os -c -isystem /home/neal/.local/lib/python3.8/site-packages/numpy/core/include -isystem /usr/include/python3.8 -std=c++17 -pthread -O3 -Wno-inline -g -fPIC -DNDEBUG -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -Iinclude build/python/cantera/_cantera.cpp
/usr/bin/python3 -c "import Cython.Build; Cython.Build.cythonize(r'build/python/cantera/_onedim.pyx', compiler_directives={'binding': True})"
Compiling build/python/cantera/_onedim.pyx because it changed.
[1/1] Cythonizing build/python/cantera/_onedim.pyx

Error compiling Cython file:
------------------------------------------------------------
...


ctypedef CxxDelegator* CxxDelegatorPtr

cdef int assign_delegates(object, CxxDelegator*) except -1
cdef void callback_v(PyFuncInfo& funcInfo) noexcept
                                          ^
------------------------------------------------------------

build/python/cantera/delegator.pxd:110:43: Syntax error in C variable declaration

Error compiling Cython file:
------------------------------------------------------------
...

import numpy as np
cimport numpy as np

from .ctcxx cimport *
from .delegator cimport CxxExternalHandle
^
------------------------------------------------------------

build/python/cantera/solutionbase.pxd:11:0: 'cantera/delegator/CxxExternalHandle.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
        void setTransport(shared_ptr[CxxTransport])
        void setTransportModel(const string&) except +translate_exception
        CxxAnyMap parameters(cbool) except +translate_exception
        size_t nAdjacent()
        shared_ptr[CxxSolution] adjacent(size_t)
        void holdExternalHandle(string&, shared_ptr[CxxExternalHandle])
                                                                    ^
------------------------------------------------------------

build/python/cantera/solutionbase.pxd:55:69: unknown type in template argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/neal/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/home/neal/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: build/python/cantera/_onedim.pyx
scons: *** [build/python/cantera/_onedim.cpp] Error 1
scons: building terminated because of errors.
```

**System information**

- Cantera version: 3.0.0a5
- OS: Ubuntu 20.04
- Python/MATLAB/other software versions: Python 3.8

This is the Scons output regarding versions of dependencies.
```

scons: Reading SConscript files ...
SCons 3.1.2 is using the following Python interpreter:
    /usr/bin/python3 (Python 3.8)
INFO: Compiling on 'Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz'
INFO: Building Cantera from git commit 'ded75f4fa'
INFO: Configuration variables read from 'cantera.conf' and command line:

Checking for C++ header file cmath... (cached) yes
Checking for C++ header file fmt/ostream.h... (cached) no
INFO: Using private installation of fmt library.
INFO: Found fmt version 9.1.0
Checking for YAML::Node().Mark()... (cached) no
INFO: Using private installation of yaml-cpp library.
Checking for C++ header file gtest/gtest.h... (cached) no
Checking for C++ header file gmock/gmock.h... (cached) no
INFO: Using Googletest from Git submodule
Checking for C++ header file eigen3/Eigen/Dense... (cached) no
Checking for C++ header file Eigen/Dense... (cached) no
INFO: Using private installation of Eigen.
INFO: Found Eigen version 
Checking whether __GLIBCXX__ is declared... (cached) yes
Checking whether __clang__ is declared... (cached) no
Checking for C++ library iomp5... (cached) no
Checking for C++ library omp... (cached) no
Checking for C++ library gomp... (cached) yes
INFO: Found Boost version 1.71
Checking for C library mkl_rt... (cached) no
Checking for C library openblas... (cached) no
Checking for C library lapack... (cached) no
INFO: No system BLAS/LAPACK libraries detected.
Checking for CVodeCreate(CV_BDF, CV_NEWTON) in C++ library sundials_cvodes... (cached) no
Checking for CVodeCreate(CV_BDF) in C++ library sundials_cvodes... (cached) no
Checking for SUNContext ctx; SUNContext_Create(0, &ctx) in C++ library sundials_cvodes... (cached) no
Checking for double x; log(x) in C library None... (cached) no
INFO: Using private installation of Sundials version 5.3.
Checking for C library hdf5... (cached) no
INFO: Using 'gfortran' to build the Fortran 90 interface
INFO: Using NumPy version 1.21.2
INFO: Using Cython version 0.29.24 (uses legacy NumPy API)
INFO: Building the full Python package for Python 3.8
scons: done reading SConscript files.
```

**Comment by speth** [comment]
You need to use Cython 0.29.31 or newer now. I just noticed this myself yesterday, and was working on a fix for this and a few other issues.

**Comment by wandadars** [comment]
> You need to use Cython 0.29.31 or newer now. I just noticed this myself yesterday, and was working on a fix for this and a few other issues.

Yes, this solved the issue.  I just ran `python -m pip install  --upgrade cython` while in my Python3.8 virtual environment, and it got past that error.
