### ISSUE TITLE
Cantera should allow for 3 temperature ranges for thermodynamic data

### ISSUE THREAD

**Issue by Nicholaswogan** [Cantera/cantera#1644]
**Problem description**

Cantera does not allow for more than two temperature ranges for thermodynamic data, yet it should, to allow entering thermodynamic data from NIST.

**Steps to reproduce**

Consider the following input file: [example.yaml.zip](https://github.com/Cantera/cantera/files/13191882/example.yaml.zip)

```python
import cantera as ct
gas = ct.Solution('example.yaml')
```

I get the error 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/python/cantera/base.pyx", line 71, in cantera._cantera._SolutionBase.__cinit__
  File "build/python/cantera/base.pyx", line 128, in cantera._cantera._SolutionBase._cinit
  File "build/python/cantera/base.pyx", line 215, in cantera._cantera._SolutionBase._init_yaml
cantera._cantera.CanteraError: 
*******************************************************************************
InputFileError thrown by AnyValue::checkSize:
Error on line 17 of ./example.yaml:
Expected array 'temperature-ranges' to have from 2 to 3 elements, but found an array of length 4.
|  Line |
|    12 | species:
|    13 | - name: H2
|    14 |   composition: {H: 2}
|    15 |   thermo:
|    16 |     model: Shomate
>    17 >     temperature-ranges: [0.0, 1000.0, 2500.0, 6000.0]
                                  ^
|    18 |     data:
|    19 |     - [33.066178, -11.36342, 11.432816, -2.772874, -0.158558, -9.980797, 172.708]
|    20 |     - [18.563083, 12.257357, -2.859786, 0.268238, 1.97799, -1.147438, 156.2881]
*******************************************************************************
```

**Behavior**

Cantera should allow for 3 temperature ranges for thermodynamic data. For example,

```yaml
- name: H2
  composition: {H: 2}
  thermo:
    model: Shomate
    temperature-ranges: [0.0, 1000.0, 2500.0, 6000.0]
    data:
    - [33.066178, -11.36342, 11.432816, -2.772874, -0.158558, -9.980797, 172.708]
    - [18.563083, 12.257357, -2.859786, 0.268238, 1.97799, -1.147438, 156.2881]
    - [43.41356, -4.293079, 1.272428, -0.096876, -20.53386, -38.51515, 162.0814]
```

**System information**

- Cantera version: 2.6.0
- OS: MacOS Apple Silicon
- Python version: 3.11.5

**Comment by Nicholaswogan** [comment]
You can see that on NIST, H2 has 3 sets of polynomials for 3 different temperature ranges: https://webbook.nist.gov/cgi/cbook.cgi?ID=C1333740&Units=SI&Mask=1#Thermo-Gas
