### ISSUE TITLE
parsing a Chemkin file with user-defined isotopes?

### ISSUE THREAD

**Issue by nickvandewiele** [Cantera/cantera#344]
An error occurs when parsing a Chemkin file with user-defined elements, e.g. `C-13` with the following code:

``` python
folder = /path/to/file

chemkinPath = os.path.join(folder, 'chem.inp')
base = os.path.basename(chemkinPath)
baseName = os.path.splitext(base)[0]
outName = os.path.join(folder, baseName + ".cti")

import cantera as ct
from cantera import ck2cti
parser = ck2cti.Parser()
parser.convertMech(chemkinFile)
model = ct.Solution(outName )
```

The chemkin file looks like this:

```
ELEMENTS
    H
    C
    CI /13.003/
END

SPECIES
    ethane(1)           ! ethane(1)
    CC(2)               ! CC(2)
END



THERM ALL
    300.000  1000.000  5000.000

ethane(1)               H 6  C 2            G100.000   5000.000  954.51        1
 4.58979653E+00 1.41508345E-02-4.75965676E-06 8.60302658E-10-6.21723639E-14    2
-1.27217512E+04-3.61719603E+00 3.78034545E+00-3.24275729E-03 5.52385248E-05    3
-6.38587529E-08 2.28639901E-11-1.16203413E+04 5.21029844E+00                   4

CC(2)                   H 6  C 1  CI1       G100.000   5000.000  954.51        1
 4.58979542E+00 1.41508364E-02-4.75965787E-06 8.60302924E-10-6.21723861E-14    2
-1.27217507E+04-2.92404261E+00 3.78034578E+00-3.24276131E-03 5.52385395E-05    3
-6.38587729E-08 2.28639990E-11-1.16203414E+04 5.90344446E+00                   4

END



REACTIONS    KCAL/MOLE   MOLES
END

```

The error trace looks like this:

```
Traceback (most recent call last):
    model = ct.Solution(outName)
  File "interfaces/cython/cantera/base.pyx", line 26, in cantera._cantera._SolutionBase.__cinit__ (interfaces/cython/cantera/_cantera.cpp:6934)
  File "interfaces/cython/cantera/base.pyx", line 62, in cantera._cantera._SolutionBase._init_cti_xml (interfaces/cython/cantera/_cantera.cpp:7470)
RuntimeError:
***********************************************************************
CanteraError thrown by addElementsFromXML:
no data for element Ci
```

Are user-defined isotopes supported in Cantera?

**Comment by speth** [comment]
Yes, user-defined species are supported in CTI files. See http://cantera.github.io/docs/sphinx/html/cti/species.html.
However, conversion of Chemkin mechanisms defining these is not currently supported.

**Comment by nickvandewiele** [comment]
great! thanks @speth !
