### ISSUE TITLE
failing tests when building Cantera 2.3.0 from source

### ISSUE THREAD

**Issue by boegel** [Cantera/cantera#432]
### Cantera version

2.3.0

### Operating System

CentOS 7.3

### Python/MATLAB version

* Python 2.7.12 (own installation)
* no MATLAB

### Expected Behavior

tests pass

### Actual Behavior

7 failing tests
* one with `Argument list too long`
* others with missing input files

I'm not sure why either of these problems occur at all, I'm not seeing an obvious potential cause...

### Steps to reproduce

1. build Cantera 2.3.0 from source using ` scons install env_vars=all CC="icc" CXX="icpc" blas_lapack_libs=mkl_rt blas_lapack_dir=$BLAS_LAPACK_LIB_DIR sundials_include=$EBROOTSUNDIALS/include sundials_libdir=$EBROOTSUNDIALS/lib prefix=$PREFIX`
2. try to run tests with `scons test env_vars=all CC="icc" CXX="icpc" blas_lapack_libs=mkl_rt blas_lapack_dir=$BLAS_LAPACK_LIB_DIR sundials_include=$EBROOTSUNDIALS/include sundials_libdir=$EBROOTSUNDIALS/lib`

```

======================================================================
FAIL: test_long_source_input (cantera.test.test_convert.CtmlConverterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 474, in test_long_source_input
    gas2 = ct.Solution(source=data_size_2048kB)
  File "interfaces/cython/cantera/base.pyx", line 29, in cantera._cantera._SolutionBase.__cinit__ (interfaces/cython/cantera/_cantera.cpp:7629)
  File "interfaces/cython/cantera/base.pyx", line 52, in cantera._cantera._SolutionBase._init_cti_xml (interfaces/cython/cantera/_cantera.cpp:8046)
CanteraError: 
***********************************************************************
CanteraError thrown by ct2ctml_string:
Error executing python while converting input file:
Python command was: '/tmp/vsc40023/software/Python/2.7.12-intel-2016b/bin/python'
exec_stream_t::start: error in child process.exec_stream_t::start: exec in child process failed. /tmp/vsc40023/software/Python/2.7.12-intel-2016b/bin/python
Argument list too long
[code 0x0007 (7)]
***********************************************************************


======================================================================
FAIL: test_gri30 (cantera.test.test_convert.chemkinConverterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 69, in test_gri30
    outName=pjoin(self.test_work_dir, 'gri30_test.cti'), quiet=True)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 14, in convertMech
    parser.convertMech(inputFile, outName=outName, **kwargs)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/ck2cti.py", line 2166, in convertMech
    raise IOError('Missing input file: {0!r}'.format(inputFile))
IOError: Missing input file: '/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/data/gri30.inp'

======================================================================
FAIL: test_transport_bad_geometry (cantera.test.test_convert.chemkinConverterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 349, in test_transport_bad_geometry
    quiet=True)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 14, in convertMech
    parser.convertMech(inputFile, outName=outName, **kwargs)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/ck2cti.py", line 2166, in convertMech
    raise IOError('Missing input file: {0!r}'.format(inputFile))
IOError: Missing input file: '/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/data/h2o2.inp'

======================================================================
FAIL: test_transport_duplicate_species (cantera.test.test_convert.chemkinConverterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 336, in test_transport_duplicate_species
    quiet=True)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 14, in convertMech
    parser.convertMech(inputFile, outName=outName, **kwargs)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/ck2cti.py", line 2166, in convertMech
    raise IOError('Missing input file: {0!r}'.format(inputFile))
IOError: Missing input file: '/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/data/h2o2.inp'

======================================================================
FAIL: test_transport_extra_column_entries (cantera.test.test_convert.chemkinConverterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 329, in test_transport_extra_column_entries
    quiet=True)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 14, in convertMech
    parser.convertMech(inputFile, outName=outName, **kwargs)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/ck2cti.py", line 2166, in convertMech
    raise IOError('Missing input file: {0!r}'.format(inputFile))
IOError: Missing input file: '/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/data/h2o2.inp'

======================================================================
FAIL: test_transport_missing_species (cantera.test.test_convert.chemkinConverterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 322, in test_transport_missing_species
    quiet=True)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 14, in convertMech
    parser.convertMech(inputFile, outName=outName, **kwargs)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/ck2cti.py", line 2166, in convertMech
    raise IOError('Missing input file: {0!r}'.format(inputFile))
IOError: Missing input file: '/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/data/h2o2.inp'

======================================================================
FAIL: test_transport_normal (cantera.test.test_convert.chemkinConverterTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 301, in test_transport_normal
    outName=pjoin(self.test_work_dir, 'h2o2_transport_normal.cti'), quiet=True)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/test_convert.py", line 14, in convertMech
    parser.convertMech(inputFile, outName=outName, **kwargs)
  File "/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/ck2cti.py", line 2166, in convertMech
    raise IOError('Missing input file: {0!r}'.format(inputFile))
IOError: Missing input file: '/tmp/vsc40023/easybuild_build/Cantera/2.3.0/intel-2016b-Python-2.7.12/cantera-2.3.0/build/python2/cantera/test/data/h2o2.inp'

----------------------------------------------------------------------
Ran 507 tests in 52.130s

FAILED (failures=7, expected failures=3)
```

**Comment by bryanwweber** [comment]
The first of those errors was fixed by 0a1257daed71fdd621ac25bcdeea911d84036bfd that got pushed the other day. I'm not sure when we'll be making a point release to fix this, but in the meantime you can cherry-pick that commit onto your 2.3 branch, hopefully it will apply without conflicts. I suspect that will also solve the rest of the errors.

**Comment by speth** [comment]
Regarding the other errors, please provide the full log from `scons build` (after running `scons clean`). Those input files should be copied to the specified folder as part of the build process.

**Comment by boegel** [comment]
@speth Hmm, I'm not running `scons build`, only `scons install` followed by `scons test` (in a build directory that is a clean unpacked source tarball). Could that be my problem? This approach worked fine with Cantera 2.2.1 (cfr. discussion in #433).

Full output is available at https://gist.github.com/boegel/4ae58f8f64bda8e7ab6e09b9b54722e0.

There's quite a bit of EasyBuild log messages in there too, so look for `scons install`

**Comment by speth** [comment]
Yes, I think not running `scons build` is the source of the problem. I think there are implicit dependencies for the `install` and `test` targets that SCons doesn't know about. I'm looking into a proper fix for this, but just running `scons build` before the other commands should have the same effect (given that build-test-install is the expected sequence of SCons commands).

**Comment by boegel** [comment]
for what it's worth: I can confirm that running `scons build` first fixes the 2nd problem I had, so in combination with backporting 0a1257d all tests now pass on my end too (except for the one covered in #433)
