### ISSUE TITLE
Floating point geometry flags cause ck2cti error

### ISSUE THREAD

**Issue by bryanwweber** [Cantera/cantera#446]
### Cantera version
2.3.0
### Operating System
Linux (but should apply to any)
### Python/MATLAB version
Any
### Expected Behavior
Parse attached transport data
### Actual Behavior
```
Traceback (most recent call last):
  File "/home/bryan/miniconda3/bin/ck2cti", line 6, in <module>
    sys.exit(cantera.ck2cti.script_entry_point())
  File "/home/bryan/miniconda3/lib/python3.6/site-packages/cantera/ck2cti.py", line 2299, in script_entry_point
    main(sys.argv[1:])
  File "/home/bryan/miniconda3/lib/python3.6/site-packages/cantera/ck2cti.py", line 2272, in main
    permissive=permissive)
  File "/home/bryan/miniconda3/lib/python3.6/site-packages/cantera/ck2cti.py", line 2204, in convertMech
    self.parseTransportData(lines, transportFile, 1)
  File "/home/bryan/miniconda3/lib/python3.6/site-packages/cantera/ck2cti.py", line 1952, in parseTransportData
    self.speciesDict[speciesName].transport = TransportData(*data, comment=comment)
  File "/home/bryan/miniconda3/lib/python3.6/site-packages/cantera/ck2cti.py", line 850, in __init__
    if int(geometry) not in (0,1,2):
ValueError: invalid literal for int() with base 10: '1.00'
```
### Steps to reproduce
1. `ck2cti --input=chem.txt --thermo=therm.txt --transport=tran.txt`

The error is because some of the geometry flags are specified as `1.00`. In Python, parsing a string to an integer with the `int` object requires the string to be a representation of an integer, it doesn't cast a floating point string representation to an integer, and instead raises that `ValueError`. It would be nice if we handled this more gracefully, either by doing the casting ourselves or by raising a helpful error message.

(Reported by Kyle Linevitch at UConn)

**Comment by speth** [comment]
- I don't see any non-integer geometry flags in the attached `tran.txt` file, so how this error is occurring is a bit unclear to me
- The attached `chem.txt` is actually the CTI file, not the Chemkin-format mechanism, so I can't test the behavior.

**Comment by bryanwweber** [comment]
Shoot... my bad. I originally uploaded the modified copies >_< The problem files are on this post.

[tran.txt](https://github.com/Cantera/cantera/files/896034/tran.txt)
[therm.txt](https://github.com/Cantera/cantera/files/896035/therm.txt)
[chem.txt](https://github.com/Cantera/cantera/files/896037/chem.txt)
