### ISSUE TITLE
Broken catalytic_combustion.py example

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#873]
**System information**

- Cantera version: development version
- OS: Ubuntu 18.04
- Python/MATLAB version: 3.6.9

**Expected behavior**

The Cantera example `catalytic_combustion.py` works without error

**Actual behavior**

The Cantera example `catalytic_combustion.py` failsr

**To Reproduce**

1. Run: `python catalytic_combustion.py`
2. See error
```
.............................................................................
Attempt Newton solution of steady-state problem...    failure. 
Take 10 timesteps   Traceback (most recent call last):
  File "catalytic_combustion.py", line 97, in <module>
    sim.solve(loglevel)
  File "interfaces/cython/cantera/onedim.pyx", line 1137, in cantera._cantera.Sim1D.solve
cantera._cantera.CanteraError: 
***********************************************************************
CanteraError thrown by OneDim::timeStep:
Time integration failed.
***********************************************************************
```
**Other:**

The example works as expected on 2.4.

**Comment by ischoegl** [comment]
PS: the problematic behavior was introduced in 1866e35 which switched the input file to YAML, i.e. it is a manifestation of an underlying bug reported in #902; the old CTI input still works.
